title: Shravan Chandrashekharaiah # your name (or website title) here
logo: "/images/profile.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Pursuing M.Sc. in Software Engineering at the University of Limerick  <br>
  Have 5+ years of work experience. Experienced in Ruby on Rails and Python technology
  <br><br>
  Professionally worked on below domain:<br>
  - OTT products(RoR).<br>
  - Newsroom(CMS) product(RoR).<br>
  - OCR Technology(Flask).<br> 
  <br><br>
  Personal Projects:<br>
  - Micro Service vod_platform in rails as a College project.<br>
  - Chat application using Action Cabel.<br>
  - OCR and NLP Project using Spacy.<br>
  - OTT platform using rails engine.<br>
  - Others<br>
  <br><br>
  Interests:<br>
  - Reading.<br>
  - Sports (Badminton, Table Tennis).<br>
 
  <a href="https://www.linkedin.com/in/shravan-chandrashekharaiah/">View My LinkedIn Profile</a> <br>
  <a href="https://medium.com/@shravan007.c">Medium Stories</a> <br> 

  
theme: jekyll-theme-minimal

